### ISSUE TITLE
依存関係にミスがあると落ちる

### ISSUE THREAD

**Issue by beet-aizu** [online-judge-tools/verification-helper#197]
https://github.com/beet-aizu/library/runs/497499857?check_suite_focus=true

CE でも❌をつける仕様の方が直感的ではないか

**Comment by beet-aizu** [comment]
https://github.com/beet-aizu/library/actions/runs/52876628 こっちは動いた　なんで？

**Comment by beet-aizu** [comment]
あーいやページビルドはやっぱり死んだままだな

**Comment by kmyk** [comment]
`docs.py` の中で死んでる


``` python
# https://github.com/beet-aizu/library/runs/497499857
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/bin/oj-verify", line 11, in <module>
    load_entry_point('online-judge-verify-helper==4.7.0', 'console_scripts', 'oj-verify')()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 184, in main
    subcommand_docs()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 145, in subcommand_docs
    onlinejudge_verify.docs.main()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 721, in main
    PagesBuilder(cpp_source_pathstr='.', config=config)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 480, in __init__
    self.remove_ignored_file_relation()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 621, in remove_ignored_file_relation
    if not self.is_ignored(depends):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 511, in is_ignored
    parser = FileParser(file_path)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 46, in __init__
    with open(file_path, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/work/library/library/test/aoj'
```

**Comment by kmyk** [comment]
> C++で、
> 
> * `.test`がファイル名に含まれていないファイルがテストされる(https://github.com/knshnb/competitive_library/runs/621356389?check_suite_focus=true)
> * `#define IGNORE`されているファイルがテストされる(https://github.com/knshnb/competitive_library/runs/620332379?check_suite_focus=true)
> 
> 自分の設定ミスだったらすいません。

https://github.com/kmyk/online-judge-verify-helper/issues/228#issue-607390841 @knshnb


> テストがされてるのでなくて、依存関係の解析をするフェイズで落ちてるように見えます。
> どのファイルがどのファイルに依存してるかや `#define IGNORE` されてるかどうかは、とりあえず一度 g++ でコンパイルしてみることで判断しています。たぶんこのときコンパイル不可能なコードに対するエラー処理をしてない (†バグ†) はずで、こんなことになっています。

https://github.com/kmyk/online-judge-verify-helper/issues/228#issuecomment-619912114 @kmyk

**Comment by kmyk** [comment]
次のあたりでエラー処理がないのが悪い:

https://github.com/kmyk/online-judge-verify-helper/blob/1efd5d905363dc8bab21abae0ac09912b8251c76/onlinejudge_verify/languages/cplusplus.py#L43-L63

@knshnb プルリクどうですか？

**Comment by kmyk** [comment]
依存関係でエラーになったときにどうするかは自明じゃないな

1. 分かりやすくエラーメッセージを出してすべて終了
   - 簡単だしデメリットはない
2. 依存なし + `#define IGNORE` 相当のものとして続行
   - これはだめ。うっかり間違えただけのやつが IGNORE されちゃまずいだろ
3. 失敗扱いにして続行。つまり、ドキュメント上のそのファイルの表示を :x: にしてかつ CI 全体の結果を失敗にする
   - 理想だけど、実装が面倒そう

**Comment by knshnb** [comment]
ん、メンションされてるの気づいてませんでした。
時間ができたら考えてみます。
