### ISSUE TITLE
oj-verify が手元で動かない

### ISSUE THREAD

**Issue by sigma425** [online-judge-tools/verification-helper#252]
$ oj-verify run や単に $ oj-verify で以下の文言が出ます

`
You use an old version of online-judge-tools (< 10.0.0) with online-judge-api-client, they are not compatible.
Please execute:

    1. Uninstall online-judge-tools and online-judge-api-client.
        $ pip3 uninstall online-judge-tools online-judge-api-client

    2. Check if they are completely uninstalled. It has successfully uninstalled when the following commands say something like "not found".
        $ command oj
        oj: command not found

        $ python3 -c 'from onlinejudge.__about__ import __version__ ; print(__version__)'
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        ModuleNotFoundError: No module named 'onlinejudge.__about__'

    3. Reinstall online-judge-tools.
        $ pip3 install online-judge-tools
`
しかし自分の環境では、この条件は満たしています
$ oj --version
online-judge-tools 10.0.3 (+ online-judge-api-client 10.0.8)

一応文言のとおりに再インストールしましたが、同じ状況です

情報:
ubuntu 18.04
試してみたら oj-bundle は動きました

**Comment by kmyk** [comment]
この文言によるエラーは「古い online-judge-tools と新しい online-judge-tools が同時にインストールされてそれらが混ざったキメラが動く」ということを防ぐためのエラーです。そちらの環境では「両方が同時にインストールされているが、新しい方しか使われてない」のにエラーになっているようで、どちらかといえば誤検出です :bow:

以下を順番に実行して、出力されたログを全部貼り付けてください。

``` console
$ pip3 uninstall online-judge-tools online-judge-api-client
$ command oj
$ python3 -c 'from onlinejudge.__about__ import __version__ ; print(__version__)'
$ python3 -c 'import pathlib, sys ; print(*[path for path in sys.path if (pathlib.Path(path) / "onlinejudge").exists()] or ["not installed"])'
$ pip3 show online-judge-tools online-judge-api-client online-judge-verify-helper
```

(上 3 行は貼ってもらった文言のステップ 1, 2 で、下 2 行は追加の情報取得です。ホームディレクトリのユーザ名とかを漏らしたくない場合はいい感じに編集してください)

**Comment by sigma425** [comment]
ありがとうございます。

```
$ pip3 uninstall online-judge-tools online-judge-api-client
Uninstalling online-judge-tools-10.0.3:
  /home/sigma/.local/bin/oj
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/INSTALLER
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/LICENSE
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/METADATA
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/RECORD
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/WHEEL
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/entry_points.txt
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_tools-10.0.3.dist-info/top_level.txt
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__about__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/__about__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/download_history.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/format_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/logging.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/main.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/update_checking.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/__pycache__/utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/download_history.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/format_utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/logging.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/main.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/download.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/generate_input.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/generate_output.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/login.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/submit.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/test.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/__pycache__/test_reactive.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/download.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/generate_input.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/generate_output.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/login.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/submit.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/test.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/subcommand/test_reactive.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/update_checking.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_command/utils.py
  /home/sigma/.local/lib/python3.6/site-packages/tests/_implementation/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/tests/_implementation/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests/_implementation/__pycache__/format_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests/_implementation/format_utils.py
Proceed (y/n)? y
  Successfully uninstalled online-judge-tools-10.0.3
Uninstalling online-judge-api-client-10.0.8:
  /home/sigma/.local/bin/oj-api
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/INSTALLER
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/LICENSE
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/METADATA
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/RECORD
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/WHEEL
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/entry_points.txt
  /home/sigma/.local/lib/python3.6/site-packages/online_judge_api_client-10.0.8.dist-info/top_level.txt
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__about__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__pycache__/__about__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__pycache__/dispatch.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__pycache__/type.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/__pycache__/utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__pycache__/format_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__pycache__/logging.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__pycache__/testcase_zipper.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/__pycache__/utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/format_utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/logging.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/testcase_zipper.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/_implementation/utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/dispatch.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/py.typed
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/anarchygolf.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/aoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/atcoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/codechef.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/codeforces.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/csacademy.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/facebook.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/google.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/hackerrank.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/kattis.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/library_checker.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/poj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/spoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/toph.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/__pycache__/yukicoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/anarchygolf.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/aoj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/atcoder.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/codechef.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/codeforces.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/csacademy.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/facebook.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/google.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/hackerrank.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/kattis.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/library_checker.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/poj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/spoj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/toph.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/service/yukicoder.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/type.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge/utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/get_contest.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/get_problem.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/get_service.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/login_service.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/main.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/__pycache__/submit_code.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/get_contest.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/get_problem.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/get_service.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/login_service.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/main.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_api/submit_code.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__about__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__pycache__/__about__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__pycache__/dispatch.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__pycache__/type.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/__pycache__/utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__pycache__/format_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__pycache__/logging.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__pycache__/testcase_zipper.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/__pycache__/utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/format_utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/logging.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/testcase_zipper.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/_implementation/utils.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/dispatch.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/py.typed
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/anarchygolf.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/aoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/atcoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/codechef.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/codeforces.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/csacademy.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/facebook.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/google.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/hackerrank.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/kattis.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/library_checker.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/poj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/spoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/toph.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/__pycache__/yukicoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/anarchygolf.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/aoj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/atcoder.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/codechef.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/codeforces.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/csacademy.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/facebook.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/google.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/hackerrank.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/kattis.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/library_checker.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/poj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/spoj.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/toph.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/service/yukicoder.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/type.py
  /home/sigma/.local/lib/python3.6/site-packages/onlinejudge_workaround_for_conflict/utils.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/dispatch.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/get_problem_aoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/get_problem_codeforces.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/get_problem_poj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/implementation_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/load_balancer.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_anarchygolf.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_aoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_atcoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_codechef.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_codeforces.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_facebook.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_google.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_library_checker.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_spoj.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/service_yukicoder.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/__pycache__/type.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/_implementation/__init__.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/_implementation/__pycache__/__init__.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/_implementation/__pycache__/format_utils.cpython-36.pyc
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/_implementation/format_utils.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/dispatch.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/get_problem_aoj.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/get_problem_codeforces.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/get_problem_poj.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/implementation_utils.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/load_balancer.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_anarchygolf.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_aoj.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_atcoder.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_codechef.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_codeforces.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_facebook.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_google.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_library_checker.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_spoj.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/service_yukicoder.py
  /home/sigma/.local/lib/python3.6/site-packages/tests_workaround_for_conflict/type.py
Proceed (y/n)? y
  Successfully uninstalled online-judge-api-client-10.0.8
```
```
$ command oj
bash: /home/sigma/.local/bin/oj: No such file or directory
```
```
$ python3 -c 'from onlinejudge.__about__ import __version__ ; print(__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'onlinejudge.__about__'
```
```
$ python3 -c 'import pathlib, sys ; print(*[path for path in sys.path if (pathlib.Path(path) / "onlinejudge").exists()] or ["not installed"])'
/home/sigma/.local/lib/python3.6/site-packages
```
```
$ pip3 show online-judge-tools online-judge-api-client online-judge-verify-helper
Name: online-judge-tools
Version: 9.2.2
Summary: Tools for online-judge services
Home-page: https://github.com/kmyk/online-judge-tools
Author: Kimiyuki Onaka
Author-email: kimiyuki95@gmail.com
License: MIT License
Location: /home/sigma/.local/lib/python3.6/site-packages
Requires: beautifulsoup4, requests, diff-match-patch, lxml, appdirs, colorama, toml
---
Name: online-judge-verify-helper
Version: 4.10.1
Summary: UNKNOWN
Home-page: https://github.com/kmyk/online-judge-verify-helper
Author: Kimiyuki Onaka
Author-email: kimiyuki95@gmail.com
License: MIT License
Location: /home/sigma/.local/lib/python3.6/site-packages
Requires: pyyaml, setuptools, toml, online-judge-tools
```

確かに最後に謎のものが表示されてますね・・・

**Comment by kmyk** [comment]
情報提供助かります。
予想外の残り方しててちょっと驚いてます。それぞれ違う場所に複数バージョンがインストールされてると思ってたのに、なぜかまったく同じ場所にインストールされてるぽいためです。

解決策ですが、`$ pip3 uninstall online-judge-tools` を追加で何度か実行してみてください。`$ pip3 show online-judge-tools` しても 9.2.2 が表示されなくなれば成功です。
それでもだめなら、最終手段として、`$ rm -rf ~/.local/lib/python3.6/site-packages/online*judge*` をして関連ファイルを直接消し飛ばせば動くようになるはずです。

**Comment by sigma425** [comment]
online-judge-tools の 9.2.2 9.2.1 7.8.0 7.2.0
online-judge-verify-helper の 4.10.1 4.9.1 が残っていて（は？）、全部消し飛ばしたあとインストールし直したら動きました！ありがとうございます。
