### ISSUE TITLE
Failed to push timestamps to protected branches

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#276]
以前は protected branch の上でも動いてたと思うんですが、もしかして最近だめになりましたか？

https://github.com/online-judge-tools/verification-helper/runs/967576804

``` console
$ oj-verify all
...
INFO:onlinejudge_verify.main:use GITHUB_TOKEN
INFO:onlinejudge_verify.main:GITHUB_ACTOR = kmyk
INFO:onlinejudge_verify.main:GITHUB_REPOSITORY = online-judge-tools/verification-helper
INFO:onlinejudge_verify.main:$ git add .verify-helper/timestamps.remote.json && git commit && git push
[master 419d408] [auto-verifier] verify commit 68fe62ed4be4e49c3dade7b18e83ea963ffe3836
 1 file changed, 3 insertions(+)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 4 of 4 required status checks are expected.        
To https://github.com/online-judge-tools/verification-helper.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/online-judge-tools/verification-helper.git'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/bin/oj-verify", line 11, in <module>
    load_entry_point('online-judge-verify-helper==4.10.3', 'console_scripts', 'oj-verify')()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 209, in main
    summary = subcommand_run(paths=[], timeout=parsed.timeout, tle=parsed.tle, jobs=parsed.jobs)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 80, in subcommand_run
    push_timestamp_to_branch()
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 100, in push_timestamp_to_branch
    subprocess.check_call(['git', 'push', url, 'HEAD'])
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', '***github.com/online-judge-tools/verification-helper.git', 'HEAD']' returned non-zero exit status 1.
##[error]Process completed with exit code 1.
```

**Comment by kmyk** [comment]
CI が通らないとマージできないようにしてあるんですが、まさにそれっぽいエラー `error: 4 of 4 required status checks are expected.`  が出てますね。これは解決無理でしょ。終了です。`Require status checks to pass before merging` の check を off に
